admin_index:
    path:     /
    defaults: { _controller: "BlogBundle:Post:index" }
    methods:  GET

admin_show:
    path:     /{id}/show
    defaults: { _controller: "BlogBundle:Post:show" }
    methods:  GET

admin_new:
    path:     /new
    defaults: { _controller: "BlogBundle:Post:new" }
    methods:  [GET, POST]

admin_edit:
    path:     /{id}/edit
    defaults: { _controller: "BlogBundle:Post:edit" }
    methods:  [GET, POST]

admin_delete:
    path:     /{id}/delete
    defaults: { _controller: "BlogBundle:Post:delete" }
    methods:  DELETE
